import type { Place } from './types';

export type Region = {
  key: string;
  label: string;
  lat: number;
  lng: number;
  radius: number;
};

export const REGIONS: Region[] = [
  { key: 'cp',           label: 'Connaught Place',  lat: 28.6315, lng: 77.2167, radius: 2000 },
  { key: 'south',        label: 'South Delhi',       lat: 28.5245, lng: 77.1855, radius: 5000 },
  { key: 'north',        label: 'North Delhi',       lat: 28.7041, lng: 77.1025, radius: 5000 },
  { key: 'central',      label: 'Central Delhi',     lat: 28.6562, lng: 77.2297, radius: 3000 },
  { key: 'chanakyapuri', label: 'Chanakyapuri',      lat: 28.5994, lng: 77.1753, radius: 2500 },
  { key: 'majnu',        label: 'Majnu Ka Tila',     lat: 28.7196, lng: 77.2309, radius: 1000 },
  { key: 'hauz',         label: 'Hauz Khas',         lat: 28.5494, lng: 77.2001, radius: 2000 },
  { key: 'lajpat',       label: 'Lajpat / Pandara',  lat: 28.5677, lng: 77.2434, radius: 2000 },
  { key: 'saket',        label: 'Saket / Kalu Sarai',lat: 28.5245, lng: 77.2066, radius: 2000 },
  { key: 'olddelhi',     label: 'Old Delhi',         lat: 28.6562, lng: 77.2297, radius: 2000 },
  { key: 'nehru',        label: 'Def Col / GK',      lat: 28.5653, lng: 77.2373, radius: 2500 },
];

export const ACCENTS: Record<string, string> = {
  'indian-accent':           '#D85A30',
  'olive-bar-kitchen':       '#1D9E75',
  'smoke-house-deli':        '#378ADD',
  'hauz-khas-social':        '#C94B8A',
  'soda-bottle-openerwala':  '#E8763A',
  'café-lota':               '#7F77DD',
  'bukhara':                 '#1D9E75',
  'diggin-cafe':             '#7F77DD',
  'farzi-cafe':              '#D4537E',
  'united-coffee-house':     '#BA7517',
  'wengers':                 '#D85A30',
  'hotel-saravana-bhavan':   '#639922',
  'karim-hotel':             '#D85A30',
  'old-jalebi-wala':         '#EF9F27',
  'paranthe-wali-gali':      '#EF9F27',
  'natraj-dahi-bhalle':      '#5DCAA5',
  'triveni-terrace':         '#7F77DD',
  'daryaganj':               '#D4537E',
  'moti-mahal':              '#D85A30',
  'chache-di-hatti':         '#BA7517',
  'wongdhen-cafe':           '#5DCAA5',
  'dolma-house':             '#378ADD',
  'andhra-bhavan':           '#639922',
  'pindi-restaurant':        '#BA7517',
  'cafe-tesu':               '#639922',
  'swagath':                 '#1D9E75',
  'punjabi-by-nature':       '#D4537E',
};

export const PLACES: Place[] = [
  // ── South Delhi ──────────────────────────────────────────────────────────
  {
    id: 'indian-accent',
    name: 'Indian Accent',
    region: 'south',
    neighbourhood: 'Lodhi Road',
    cuisine: ['indian', 'fusion'],
    vibe: ['finedining', 'romantic'],
    price: 4, rating: 4.7, ratingCount: '7.7k',
    location: 'Lodhi Road, South Delhi',
    intro: "Delhi's most celebrated restaurant — modern Indian tasting menus that reimagine tradition with startling elegance.",
    famous: "Potato Sphere Chaat · Meetha Achaar Pork Ribs · Chef's Tasting Menu",
    tip: 'Book 2 weeks ahead. Always go for the tasting menu.',
    hours: '12–2:30 PM · 6:45–9 PM',
    lat: 28.5918, lng: 77.2382,
    photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    mustTry: true,
  },
  {
    id: 'olive-bar-kitchen',
    name: 'Olive Bar & Kitchen',
    region: 'south',
    neighbourhood: 'Mehrauli',
    cuisine: ['continental', 'fusion'],
    vibe: ['romantic', 'finedining'],
    price: 4, rating: 4.3, ratingCount: '5.1k',
    location: 'Mehrauli, South Delhi',
    intro: 'Mediterranean dining beside the Qutub Minar — whitewashed walls, fairy lights, exceptional food.',
    famous: 'Wood-fired Pizza · Lamb Chops · Sunday Brunch',
    tip: 'Sit outside on a winter night with the Qutub lit up. Pure magic.',
    hours: '12:30–3 PM · 7 PM–12 AM',
    lat: 28.5244, lng: 77.1855,
    photo: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
  },

  // ── Hauz Khas ────────────────────────────────────────────────────────────
  {
    id: 'smoke-house-deli',
    name: 'Smoke House Deli',
    region: 'hauz',
    neighbourhood: 'Hauz Khas Village',
    cuisine: ['continental', 'cafe'],
    vibe: ['casual', 'artsy'],
    price: 3, rating: 4.2, ratingCount: '8.3k',
    location: 'Hauz Khas Village',
    intro: 'Rustic-chic deli in the heart of Hauz Khas — smoked meats, artisanal sandwiches, craft beer.',
    famous: 'Smoked Chicken Sandwich · Truffle Mac & Cheese · Craft Beer',
    tip: 'Grab a window table overlooking the village lane. Great for long lunches.',
    hours: '12 PM – 1 AM daily',
    lat: 28.5494, lng: 77.2001,
    photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
  },
  {
    id: 'hauz-khas-social',
    name: 'Hauz Khas Social',
    region: 'hauz',
    neighbourhood: 'Hauz Khas Village',
    cuisine: ['fusion', 'cafe'],
    vibe: ['casual', 'artsy'],
    price: 2, rating: 4.1, ratingCount: '22k',
    location: 'Hauz Khas Village',
    intro: 'The OG Social — co-working by day, party by night, with a killer view of the Hauz Khas lake.',
    famous: 'Social Platter · LIIT Cocktail · Sichuan Chilli Chicken',
    tip: 'Come at sunset. The view over the lake from the terrace is unbeatable.',
    hours: '11 AM – 1 AM daily',
    lat: 28.5505, lng: 77.1991,
    photo: 'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=600&q=80',
  },
  {
    id: 'soda-bottle-openerwala',
    name: 'SodaBottleOpenerWala',
    region: 'hauz',
    neighbourhood: 'Khan Market',
    cuisine: ['indian', 'cafe'],
    vibe: ['casual', 'artsy'],
    price: 3, rating: 4.3, ratingCount: '11k',
    location: 'Khan Market',
    intro: 'Iconic Irani cafe vibes — Parsi food, bun maska, and the warmest chai in a nostalgic setting.',
    famous: 'Keema Pav · Salli Boti · Bun Maska with Chai · Dhansak',
    tip: 'Order the Dhansak. The whole place smells like Old Bombay.',
    hours: '8:30 AM – 11 PM daily',
    lat: 28.5999, lng: 77.2266,
    photo: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600&q=80',
  },

  // ── Central Delhi ────────────────────────────────────────────────────────
  {
    id: 'café-lota',
    name: 'Café Lota',
    region: 'central',
    neighbourhood: 'Pragati Maidan',
    cuisine: ['indian', 'cafe'],
    vibe: ['artsy', 'casual'],
    price: 2, rating: 4.4, ratingCount: '9.2k',
    location: 'National Crafts Museum, Pragati Maidan',
    intro: 'A design museum cafe celebrating Indian regional food in a stunning open courtyard.',
    famous: 'Broken Wheat Khichdi · Moong Dal Halwa · Gunpowder Dosa',
    tip: 'Visit the Crafts Museum first, then eat here. The outdoor seating is serene.',
    hours: '9 AM – 7:30 PM (closed Mon)',
    lat: 28.6127, lng: 77.2417,
    photo: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80',
  },
  {
    id: 'triveni-terrace',
    name: 'Triveni Terrace Cafe',
    region: 'central',
    neighbourhood: 'Mandi House',
    cuisine: ['indian', 'cafe'],
    vibe: ['artsy', 'casual'],
    price: 2, rating: 4.4, ratingCount: '6.5k',
    location: 'Mandi House, Central Delhi',
    intro: 'Hidden beside a cultural arts complex — chai, chaat, and the Delhi art crowd.',
    famous: 'Palak Patta Chaat · Bun Tikki · Masala Chai',
    tip: 'Sit in the courtyard on a cool evening. Bring a book or a friend.',
    hours: '10 AM – 9:30 PM daily',
    lat: 28.6268, lng: 77.2311,
    photo: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600&q=80',
  },

  // ── Chanakyapuri ─────────────────────────────────────────────────────────
  {
    id: 'bukhara',
    name: 'Bukhara',
    region: 'chanakyapuri',
    neighbourhood: 'ITC Maurya',
    cuisine: ['indian'],
    vibe: ['finedining'],
    price: 4, rating: 4.5, ratingCount: '9.1k',
    location: 'ITC Maurya, Chanakyapuri',
    intro: 'Legendary since 1978 — dal bukhara and tandoori classics cooked over charcoal.',
    famous: 'Dal Bukhara (slow-cooked 18 hrs) · Sikandari Raan · Tandoori Prawns',
    tip: "Eat with your hands as tradition dictates. The dal alone is worth the trip.",
    hours: '12:30–2:45 PM · 7–11:45 PM',
    lat: 28.5994, lng: 77.1753,
    photo: 'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=600&q=80',
    mustTry: true,
  },
  {
    id: 'diggin-cafe',
    name: 'Diggin Cafe',
    region: 'chanakyapuri',
    neighbourhood: 'Santushti Complex',
    cuisine: ['continental', 'cafe'],
    vibe: ['romantic', 'casual'],
    price: 3, rating: 4.4, ratingCount: '16.7k',
    location: 'Santushti, Chanakyapuri',
    intro: 'A garden tucked inside an Air Force complex — pizza, pasta and pure green serenity.',
    famous: 'Farm Veggie Pizza · Oreo Shake · Seasonal Garden Brunches',
    tip: "Carry government-issued ID — it's inside an Air Force station.",
    hours: '11 AM – 9:30 PM daily',
    lat: 28.5951, lng: 77.1841,
    photo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
  },

  // ── Connaught Place ──────────────────────────────────────────────────────
  {
    id: 'farzi-cafe',
    name: 'Farzi Cafe',
    region: 'cp',
    neighbourhood: 'Connaught Place',
    cuisine: ['fusion', 'indian'],
    vibe: ['casual', 'romantic'],
    price: 3, rating: 4.0, ratingCount: '10.2k',
    location: 'Connaught Place',
    intro: 'Molecular Indian cuisine where your dal arrives as arancini and bao hides butter chicken.',
    famous: 'Dal Chawal Arancini · Butter Chicken Bao · Farzi Dirt Pile dessert',
    tip: 'Come after 8 PM for live music. The desserts are theatrical — save room.',
    hours: '12 PM – 1 AM daily',
    lat: 28.6315, lng: 77.2167,
    photo: 'https://images.unsplash.com/photo-1567529692333-de9fd6772897?w=600&q=80',
  },
  {
    id: 'united-coffee-house',
    name: 'United Coffee House',
    region: 'cp',
    neighbourhood: 'Connaught Place',
    cuisine: ['indian', 'continental'],
    vibe: ['casual', 'finedining'],
    price: 3, rating: 4.2, ratingCount: '7.8k',
    location: 'E Block, Connaught Place',
    intro: 'Since 1942 — a grand colonial cafe that has served diplomats, artists and every Delhiite with nostalgia.',
    famous: 'Chicken a la Kiev · Mutton Seekh Kebab · Club Sandwich',
    tip: 'Sit in the main hall under the chandeliers. Order the club sandwich and cold coffee.',
    hours: '10 AM – 11 PM daily',
    lat: 28.6329, lng: 77.2195,
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
  },
  {
    id: 'wengers',
    name: "Wenger's Deli",
    region: 'cp',
    neighbourhood: 'Connaught Place',
    cuisine: ['continental', 'cafe'],
    vibe: ['casual', 'budget'],
    price: 2, rating: 4.3, ratingCount: '13k',
    location: 'A Block, Connaught Place',
    intro: "Since 1926 — Delhi's oldest bakery and the best place for patties, pastries and nostalgia.",
    famous: 'Chicken Patty · Plum Cake · Cheese Straws',
    tip: 'Always a queue but always worth it. Buy a box of cheese straws to take home.',
    hours: '10 AM – 8 PM (closed Mon)',
    lat: 28.6339, lng: 77.2182,
    photo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
  },
  {
    id: 'hotel-saravana-bhavan',
    name: 'Saravana Bhavan',
    region: 'cp',
    neighbourhood: 'Janpath',
    cuisine: ['indian', 'street'],
    vibe: ['casual', 'budget'],
    price: 1, rating: 4.4, ratingCount: '18k',
    location: 'Janpath, Connaught Place',
    intro: 'The world-famous South Indian chain — the most consistent masala dosa in Delhi, period.',
    famous: 'Masala Dosa · Idli Sambar · Filter Coffee · Rava Kesari',
    tip: 'Go for breakfast. The filter coffee alone is worth the trip.',
    hours: '8 AM – 11 PM daily',
    lat: 28.6279, lng: 77.2201,
    photo: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80',
  },

  // ── Old Delhi ────────────────────────────────────────────────────────────
  {
    id: 'karim-hotel',
    name: "Karim's",
    region: 'olddelhi',
    neighbourhood: 'Jama Masjid',
    cuisine: ['indian', 'street'],
    vibe: ['casual', 'budget'],
    price: 2, rating: 4.3, ratingCount: '31k',
    location: 'Gali Kababian, Jama Masjid',
    intro: "Since 1913 — the most legendary kebab house in Delhi, hidden in a lane behind Jama Masjid.",
    famous: 'Mutton Burra · Nihari · Seekh Kebab · Mutton Nahari',
    tip: 'Go for breakfast nihari on a Sunday. The mutton burra is non-negotiable.',
    hours: '9 AM – 12 AM daily',
    lat: 28.6507, lng: 77.2334,
    photo: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80',
    mustTry: true,
  },
  {
    id: 'old-jalebi-wala',
    name: 'Old Famous Jalebi Wala',
    region: 'olddelhi',
    neighbourhood: 'Chandni Chowk',
    cuisine: ['street'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.0, ratingCount: '8.8k',
    location: 'Dariba Kalan, Chandni Chowk',
    intro: 'Since 1884 — the original desi ghee jalebi, secret recipe passed through five generations.',
    famous: 'Crispy Desi Ghee Jalebi · Jalebi-Rabri combo · Samosa',
    tip: 'Pair jalebis with cold rabri. Go early — they sell out by afternoon weekends.',
    hours: '8 AM – 9:30 PM daily',
    lat: 28.6562, lng: 77.2297,
    photo: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80',
  },
  {
    id: 'paranthe-wali-gali',
    name: 'Paranthe Wali Gali',
    region: 'olddelhi',
    neighbourhood: 'Chandni Chowk',
    cuisine: ['street', 'indian'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.1, ratingCount: '14k',
    location: 'Paranthe Wali Gali, Chandni Chowk',
    intro: 'A lane dedicated to stuffed paranthas — 150+ years old, fillings from rabri to dry fruit.',
    famous: 'Rabri Parantha · Banana Parantha · Khurchan Parantha',
    tip: 'Try at least 3 different fillings. Pair with pickle and thick dahi.',
    hours: '7 AM – 10 PM daily',
    lat: 28.6566, lng: 77.2290,
    photo: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80',
  },
  {
    id: 'natraj-dahi-bhalle',
    name: 'Natraj Dahi Bhalle',
    region: 'olddelhi',
    neighbourhood: 'Chandni Chowk',
    cuisine: ['street'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.5, ratingCount: '6.7k',
    location: 'Chandni Chowk Main Road',
    intro: "The single best dahi bhalle in Delhi — one dish, perfected since 1940.",
    famous: 'Dahi Bhalle · Aloo Tikki Chaat',
    tip: 'Just order the dahi bhalle. One dish, perfected over 80 years.',
    hours: '9 AM – 9 PM (closed Sun)',
    lat: 28.6558, lng: 77.2301,
    photo: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=600&q=80',
  },

  // ── North Delhi ──────────────────────────────────────────────────────────
  {
    id: 'daryaganj',
    name: 'Daryaganj',
    region: 'north',
    neighbourhood: 'Tagore Garden',
    cuisine: ['indian'],
    vibe: ['casual', 'finedining'],
    price: 3, rating: 4.7, ratingCount: '3.3k',
    location: 'Tagore Garden, North Delhi',
    intro: "The self-proclaimed inventors of Butter Chicken and Dal Makhani — the original recipes.",
    famous: 'Original Butter Chicken · Dal Makhani · Missi Roti',
    tip: 'Order the Butter Chicken + Roomali Roti combo. Then decide for yourself.',
    hours: '12 PM – 11 PM daily',
    lat: 28.6659, lng: 77.1333,
    photo: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80',
    mustTry: true,
  },
  {
    id: 'moti-mahal',
    name: 'Moti Mahal',
    region: 'north',
    neighbourhood: 'Daryaganj',
    cuisine: ['indian'],
    vibe: ['casual', 'budget'],
    price: 2, rating: 4.0, ratingCount: '5.2k',
    location: 'Netaji Subhash Marg, Daryaganj',
    intro: 'The original home of butter chicken — opened in 1947, this is where it all started.',
    famous: 'Butter Chicken · Tandoori Chicken · Dal Makhani',
    tip: 'The OG location. A bit rough around the edges but the food tells the history.',
    hours: '11 AM – 11 PM daily',
    lat: 28.6469, lng: 77.2395,
    photo: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
  },
  {
    id: 'chache-di-hatti',
    name: 'Chache Di Hatti',
    region: 'north',
    neighbourhood: 'Kamla Nagar',
    cuisine: ['street', 'indian'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.3, ratingCount: '4.9k',
    location: 'Kamla Nagar, North Delhi',
    intro: "North Delhi's most obsessed-over chole bhature — potato stuffed, always a queue.",
    famous: 'Pindi Chole Bhature · Aloo-stuffed Bhature · Free chole refills',
    tip: 'Go before noon. Worth every minute of the queue.',
    hours: '9:30 AM – 3 PM (closed Sun)',
    lat: 28.6826, lng: 77.2081,
    photo: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80',
  },

  // ── Majnu Ka Tila ────────────────────────────────────────────────────────
  {
    id: 'wongdhen-cafe',
    name: 'Wongdhen Cafe',
    region: 'majnu',
    neighbourhood: 'Majnu Ka Tila',
    cuisine: ['asian'],
    vibe: ['casual', 'artsy'],
    price: 2, rating: 4.4, ratingCount: '2k',
    location: 'Majnu Ka Tila',
    intro: "Delhi's Little Tibet — momos, sushi and Japanese cheesecake with live acoustic sets.",
    famous: 'Corn Spring Onion Dim Sum · Japanese Cheesecake · Crispy Honey Chicken',
    tip: 'The Japanese cheesecake is exceptional. Walk the Tibetan lanes before eating.',
    hours: '8 AM – 10:30 PM daily',
    lat: 28.7196, lng: 77.2309,
    photo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
  },
  {
    id: 'dolma-house',
    name: 'Dolma House',
    region: 'majnu',
    neighbourhood: 'Majnu Ka Tila',
    cuisine: ['asian'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.3, ratingCount: '1.8k',
    location: 'Majnu Ka Tila',
    intro: 'A beloved Tibetan home-kitchen serving the most authentic thukpa and momos in Delhi.',
    famous: 'Beef Thukpa · Steam Momos · Butter Tea',
    tip: 'Tiny space, big flavours. Go hungry. Try the butter tea — acquired taste, worth it.',
    hours: '9 AM – 9 PM daily',
    lat: 28.7190, lng: 77.2315,
    photo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },

  // ── Lajpat / Pandara ─────────────────────────────────────────────────────
  {
    id: 'andhra-bhavan',
    name: 'Andhra Bhavan Canteen',
    region: 'lajpat',
    neighbourhood: 'Ashoka Road',
    cuisine: ['indian', 'street'],
    vibe: ['budget', 'casual'],
    price: 1, rating: 4.6, ratingCount: '12k',
    location: 'Ashoka Road, Central Delhi',
    intro: 'The most under-the-radar legendary meal in Delhi — Andhra thali at state government prices.',
    famous: 'Andhra Thali · Pesarattu · Gongura Mutton',
    tip: 'Go for lunch only (12–2 PM). Arrive early — the thalis sell out. Under ₹100.',
    hours: '12 PM – 3 PM (lunch only)',
    lat: 28.6199, lng: 77.2090,
    photo: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=600&q=80',
    mustTry: true,
  },
  {
    id: 'pindi-restaurant',
    name: 'Pindi Restaurant',
    region: 'lajpat',
    neighbourhood: 'Pandara Road',
    cuisine: ['indian'],
    vibe: ['casual'],
    price: 3, rating: 4.2, ratingCount: '4.4k',
    location: 'Pandara Road Market',
    intro: "A Pandara Road institution since 1949 — old-school North Indian comfort food at its finest.",
    famous: 'Dal Makhani · Pindi Chana · Makki di Roti',
    tip: 'Pandara Road has many good spots. Pindi wins for the dal. Go after 8 PM.',
    hours: '12 PM – 12 AM daily',
    lat: 28.5994, lng: 77.2153,
    photo: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
  },

  // ── Saket / Kalu Sarai ───────────────────────────────────────────────────
  {
    id: 'cafe-tesu',
    name: 'Cafe Tesu',
    region: 'saket',
    neighbourhood: 'Kalu Sarai',
    cuisine: ['continental', 'cafe'],
    vibe: ['casual', 'artsy'],
    price: 3, rating: 4.3, ratingCount: '5.3k',
    location: 'Kalu Sarai, near Saket',
    intro: 'An all-day neighbourhood cafe that does breakfast as seriously as late-night tapas.',
    famous: 'Eggs Benedict · Mac & Cheese with Bacon · Kashmiri Kahwa',
    tip: 'The 8 AM breakfast crowd is half the charm. Tapas menu kicks in after 8 PM.',
    hours: '8 AM – 12 AM daily',
    lat: 28.5433, lng: 77.2066,
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
  },

  // ── Defence Colony / GK ──────────────────────────────────────────────────
  {
    id: 'swagath',
    name: 'Swagath Restaurant',
    region: 'nehru',
    neighbourhood: 'Defence Colony',
    cuisine: ['indian'],
    vibe: ['casual', 'finedining'],
    price: 3, rating: 4.4, ratingCount: '6.8k',
    location: 'Defence Colony',
    intro: 'The best coastal seafood in landlocked Delhi — Mangalorean and Chettinad done perfectly.',
    famous: 'Crab Gassi · Prawn Ghee Roast · Neer Dosa',
    tip: 'Order the crab gassi with neer dosa. Call ahead for the crab — it sells out.',
    hours: '12–3:30 PM · 7–11 PM daily',
    lat: 28.5653, lng: 77.2373,
    photo: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80',
  },
  {
    id: 'punjabi-by-nature',
    name: 'Punjabi By Nature',
    region: 'nehru',
    neighbourhood: 'Connaught Place',
    cuisine: ['indian'],
    vibe: ['casual', 'finedining'],
    price: 3, rating: 4.1, ratingCount: '9.1k',
    location: 'Connaught Place & multiple locations',
    intro: 'Upscale Punjabi food with a theatrical twist — butter chicken arrives in a surahi.',
    famous: 'Surahi Butter Chicken · Patiala Peg Cocktails · Amritsari Kulcha',
    tip: 'The cocktail menu is as good as the food. Try the Patiala Peg.',
    hours: '12 PM – 12 AM daily',
    lat: 28.6315, lng: 77.2167,
    photo: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80',
  },
];
