import type { Place } from './types'

export const ACCENTS: Record<string, string> = {
  'indian-accent':           '#D85A30',
  'olive-bar-kitchen':       '#1D9E75',
  'smoke-house-deli':        '#378ADD',
  'hauz-khas-social':        '#C94B8A',
  'soda-bottle-openerwala':  '#E8763A',
  'café-lota':               '#7F77DD',
  'bukhara':                 '#8B5E3C',
  'diggin-cafe':             '#7F77DD',
  'farzi-cafe':              '#D4537E',
  'united-coffee-house':     '#BA7517',
  'wengers':                 '#D85A30',
  'saravana-bhavan':         '#639922',
  'karim-hotel':             '#8B1A1A',
  'old-jalebi-wala':         '#EF9F27',
  'paranthe-wali-gali':      '#D97706',
  'natraj-dahi-bhalle':      '#5DCAA5',
  'triveni-terrace':         '#7F77DD',
  'daryaganj':               '#D4537E',
  'moti-mahal':              '#D85A30',
  'chache-di-hatti':         '#BA7517',
  'wongdhen-cafe':           '#5DCAA5',
  'dolma-house':             '#378ADD',
  'andhra-bhavan':           '#639922',
  'pindi-restaurant':        '#BA7517',
  'cafe-tesu':               '#639922',
  'swagath':                 '#1D9E75',
  'punjabi-by-nature':       '#D4537E',
}

export const PLACES: Place[] = [
  {
    id: 'indian-accent', name: 'Indian Accent',
    region: 'south', neighbourhood: 'Lodhi Road',
    cuisine: ['indian','fusion'], vibe: ['finedining','romantic'],
    type: 'Modern Indian Restaurant',
    price: 4, priceLevel: 4, rating: 4.7, ratingCount: 7700,
    location: 'Lodhi Road, South Delhi', address: 'The Lodhi, Lodhi Road, New Delhi',
    lat: 28.5918, lng: 77.2382,
    intro: "Delhi's most celebrated restaurant — modern Indian tasting menus that reimagine tradition.",
    summary: "Delhi's most celebrated restaurant — modern Indian tasting menus that reimagine tradition.",
    famous: 'Potato Sphere Chaat, Meetha Achaar Pork Ribs, Tasting Menu',
    tip: 'Book 2 weeks ahead. Always go for the tasting menu.',
    hours: 'Mon–Sun: 12–2:30 PM, 6:45–9 PM',
    hoursToday: '12:00 PM – 2:30 PM, 6:45 PM – 9:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Indian+Accent/@28.5918,77.2382',
    keywords: ['fine dining','tasting menu','modern indian','chaat','anniversary','upscale'],
    mustTry: true,
  },
  {
    id: 'bukhara', name: 'Bukhara',
    region: 'chanakyapuri', neighbourhood: 'ITC Maurya',
    cuisine: ['indian'], vibe: ['finedining'],
    type: 'North Indian Restaurant',
    price: 4, priceLevel: 4, rating: 4.5, ratingCount: 9100,
    location: 'ITC Maurya, Chanakyapuri', address: 'ITC Maurya, Diplomatic Enclave, Chanakyapuri',
    lat: 28.5994, lng: 77.1753,
    intro: 'Legendary since 1978 — dal bukhara and tandoori classics cooked over charcoal.',
    summary: 'Legendary since 1978 — dal bukhara and tandoori classics cooked over charcoal.',
    famous: 'Dal Bukhara, Sikandari Raan, Tandoori Prawns',
    tip: 'Eat with your hands as tradition dictates.',
    hours: 'Mon–Sun: 12:30–2:45 PM, 7–11:45 PM',
    hoursToday: '12:30 PM – 2:45 PM, 7:00 PM – 11:45 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Bukhara/@28.5994,77.1753',
    keywords: ['dal bukhara','tandoor','kebab','charcoal','heritage','1978'],
    mustTry: true,
  },
  {
    id: 'diggin-cafe', name: 'Diggin Cafe',
    region: 'chanakyapuri', neighbourhood: 'Santushti Complex',
    cuisine: ['continental','cafe'], vibe: ['romantic','casual'],
    type: 'Cafe',
    price: 3, priceLevel: 3, rating: 4.4, ratingCount: 16700,
    location: 'Santushti, Chanakyapuri', address: 'Santushti Shopping Complex, Chanakyapuri',
    lat: 28.5951, lng: 77.1841,
    intro: 'A garden tucked inside an Air Force complex — pizza, pasta and pure green serenity.',
    summary: 'A garden tucked inside an Air Force complex — pizza, pasta and pure green serenity.',
    famous: 'Farm Veggie Pizza, Oreo Shake, Pasta, Garden Brunch',
    tip: 'Carry government-issued ID — inside an Air Force station.',
    hours: 'Mon–Sun: 11 AM – 9:30 PM',
    hoursToday: '11:00 AM – 9:30 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Diggin/@28.5951,77.1841',
    keywords: ['pizza','pasta','garden','outdoor','brunch','romantic','dog friendly'],
  },
  {
    id: 'smoke-house-deli', name: 'Smoke House Deli',
    region: 'hauz', neighbourhood: 'Hauz Khas Village',
    cuisine: ['continental','cafe'], vibe: ['casual','artsy'],
    type: 'Deli & Bar',
    price: 3, priceLevel: 3, rating: 4.2, ratingCount: 8300,
    location: 'Hauz Khas Village', address: 'Hauz Khas Village, New Delhi',
    lat: 28.5494, lng: 77.2001,
    intro: 'Rustic-chic deli in the heart of Hauz Khas — smoked meats, artisanal sandwiches, craft beer.',
    summary: 'Rustic-chic deli — smoked meats, artisanal sandwiches, craft beer.',
    famous: 'Smoked Chicken Sandwich, Truffle Mac and Cheese, Craft Beer',
    tip: 'Grab a window table overlooking the village lane.',
    hours: 'Mon–Sun: 12 PM – 1 AM',
    hoursToday: '12:00 PM – 1:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Smoke+House+Deli/@28.5494,77.2001',
    keywords: ['smoked','sandwich','deli','craft beer','truffle','mac cheese'],
  },
  {
    id: 'hauz-khas-social', name: 'Hauz Khas Social',
    region: 'hauz', neighbourhood: 'Hauz Khas Village',
    cuisine: ['fusion','cafe'], vibe: ['casual','artsy'],
    type: 'Bar & Restaurant',
    price: 2, priceLevel: 2, rating: 4.1, ratingCount: 22000,
    location: 'Hauz Khas Village', address: '9A & 12, Hauz Khas Village, New Delhi',
    lat: 28.5505, lng: 77.1991,
    intro: 'The OG Social — co-working by day, party by night, killer lake view.',
    summary: 'The OG Social — co-working by day, party by night, killer lake view.',
    famous: 'Social Platter, LIIT, Sichuan Chilli Chicken, Cocktails',
    tip: 'Come at sunset — the view over the lake is unbeatable.',
    hours: 'Mon–Sun: 11 AM – 1 AM',
    hoursToday: '11:00 AM – 1:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Hauz+Khas+Social/@28.5505,77.1991',
    keywords: ['cocktails','party','nightlife','lake view','terrace','liit'],
  },
  {
    id: 'soda-bottle-openerwala', name: 'SodaBottleOpenerWala',
    region: 'hauz', neighbourhood: 'Khan Market',
    cuisine: ['indian','cafe'], vibe: ['casual','artsy'],
    type: 'Irani Cafe',
    price: 3, priceLevel: 3, rating: 4.3, ratingCount: 11000,
    location: 'Khan Market', address: 'Khan Market, New Delhi',
    lat: 28.5999, lng: 77.2266,
    intro: 'Iconic Irani cafe vibes — Parsi food, bun maska, warmest chai in a nostalgic setting.',
    summary: 'Iconic Irani cafe — Parsi food, bun maska, warmest chai.',
    famous: 'Keema Pav, Salli Boti, Bun Maska, Dhansak, Masala Chai',
    tip: 'Order the Dhansak. The whole place smells like Old Bombay.',
    hours: 'Mon–Sun: 8:30 AM – 11 PM',
    hoursToday: '8:30 AM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/SodaBottleOpenerWala/@28.5999,77.2266',
    keywords: ['parsi','irani','keema pav','dhansak','bun maska','chai','bombay'],
  },
  {
    id: 'café-lota', name: 'Café Lota',
    region: 'central', neighbourhood: 'Pragati Maidan',
    cuisine: ['indian','cafe'], vibe: ['artsy','casual'],
    type: 'Cafe',
    price: 2, priceLevel: 2, rating: 4.4, ratingCount: 9200,
    location: 'Pragati Maidan', address: 'National Crafts Museum, Pragati Maidan, New Delhi',
    lat: 28.6127, lng: 77.2417,
    intro: 'A design museum cafe celebrating Indian regional food in a stunning open courtyard.',
    summary: 'Museum cafe celebrating Indian regional food in a beautiful courtyard.',
    famous: 'Broken Wheat Khichdi, Moong Dal Halwa, Gunpowder Dosa',
    tip: 'Visit the Crafts Museum first, then eat here.',
    hours: 'Tue–Sun: 9 AM – 7:30 PM',
    hoursToday: '9:00 AM – 7:30 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Cafe+Lota/@28.6127,77.2417',
    keywords: ['khichdi','dosa','halwa','thali','regional','courtyard','museum','vegetarian'],
  },
  {
    id: 'triveni-terrace', name: 'Triveni Terrace Cafe',
    region: 'central', neighbourhood: 'Mandi House',
    cuisine: ['indian','cafe'], vibe: ['artsy','casual'],
    type: 'Cafe',
    price: 2, priceLevel: 2, rating: 4.4, ratingCount: 6500,
    location: 'Mandi House, Central Delhi', address: 'Triveni Kala Sangam, Mandi House, New Delhi',
    lat: 28.6268, lng: 77.2311,
    intro: 'Hidden beside a cultural arts complex — chai, chaat, and the Delhi art crowd.',
    summary: 'Hidden beside a cultural arts complex — chai, chaat, art crowd.',
    famous: 'Palak Patta Chaat, Bun Tikki, Masala Chai',
    tip: 'Sit in the courtyard on a cool evening.',
    hours: 'Mon–Sun: 10 AM – 9:30 PM',
    hoursToday: '10:00 AM – 9:30 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Triveni+Terrace+Cafe/@28.6268,77.2311',
    keywords: ['chaat','chai','samosa','courtyard','artsy','cultural','calm'],
  },
  {
    id: 'farzi-cafe', name: 'Farzi Cafe',
    region: 'cp', neighbourhood: 'Connaught Place',
    cuisine: ['fusion','indian'], vibe: ['casual','romantic'],
    type: 'Fusion Restaurant',
    price: 3, priceLevel: 3, rating: 4.0, ratingCount: 10200,
    location: 'Connaught Place', address: 'Cyber Hub / CP, Connaught Place, New Delhi',
    lat: 28.6315, lng: 77.2167,
    intro: 'Molecular Indian cuisine where dal arrives as arancini and bao hides butter chicken.',
    summary: 'Molecular Indian — dal as arancini, butter chicken bao, theatrical desserts.',
    famous: 'Dal Chawal Arancini, Butter Chicken Bao, Farzi Dirt Pile',
    tip: 'Come after 8 PM for live music.',
    hours: 'Mon–Sun: 12 PM – 1 AM',
    hoursToday: '12:00 PM – 1:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1567529692333-de9fd6772897?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Farzi+Cafe/@28.6315,77.2167',
    keywords: ['molecular','arancini','bao','butter chicken','cocktails','live music','fusion'],
  },
  {
    id: 'united-coffee-house', name: 'United Coffee House',
    region: 'cp', neighbourhood: 'Connaught Place',
    cuisine: ['indian','continental'], vibe: ['casual','finedining'],
    type: 'Heritage Restaurant',
    price: 3, priceLevel: 3, rating: 4.2, ratingCount: 7800,
    location: 'E Block, Connaught Place', address: 'E-15, Connaught Place, New Delhi',
    lat: 28.6329, lng: 77.2195,
    intro: 'Since 1942 — a grand colonial cafe that has served diplomats and every Delhiite.',
    summary: 'Since 1942 — grand colonial cafe, chandeliers, diplomats, nostalgia.',
    famous: 'Chicken a la Kiev, Mutton Seekh Kebab, Club Sandwich',
    tip: 'Sit in the main hall under the chandeliers.',
    hours: 'Mon–Sun: 10 AM – 11 PM',
    hoursToday: '10:00 AM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/United+Coffee+House/@28.6329,77.2195',
    keywords: ['colonial','heritage','chandelier','club sandwich','cold coffee','1942'],
  },
  {
    id: 'wengers', name: "Wenger's Deli",
    region: 'cp', neighbourhood: 'Connaught Place',
    cuisine: ['continental','cafe'], vibe: ['casual','budget'],
    type: 'Bakery & Deli',
    price: 2, priceLevel: 2, rating: 4.3, ratingCount: 13000,
    location: 'A Block, Connaught Place', address: 'A-16, Connaught Place, New Delhi',
    lat: 28.6339, lng: 77.2182,
    intro: "Since 1926 — Delhi's oldest bakery, best place for patties, pastries and nostalgia.",
    summary: "Since 1926 — Delhi's oldest bakery. Patties, pastries, nostalgia.",
    famous: 'Chicken Patty, Plum Cake, Cheese Straws',
    tip: 'Always a queue but always worth it.',
    hours: 'Mon–Sat: 10 AM – 8 PM',
    hoursToday: '10:00 AM – 8:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Wengers/@28.6339,77.2182',
    keywords: ['bakery','patty','pastry','plum cake','cheese straws','1926','british'],
  },
  {
    id: 'saravana-bhavan', name: 'Saravana Bhavan',
    region: 'cp', neighbourhood: 'Janpath',
    cuisine: ['indian','street'], vibe: ['casual','budget'],
    type: 'South Indian Restaurant',
    price: 1, priceLevel: 1, rating: 4.4, ratingCount: 18000,
    location: 'Janpath, Connaught Place', address: 'Janpath, Connaught Place, New Delhi',
    lat: 28.6279, lng: 77.2201,
    intro: 'The world-famous South Indian chain — most consistent masala dosa in Delhi.',
    summary: 'World-famous South Indian. Most consistent masala dosa in Delhi.',
    famous: 'Masala Dosa, Idli Sambar, Filter Coffee, Rava Kesari',
    tip: 'Go for breakfast. The filter coffee alone is worth it.',
    hours: 'Mon–Sun: 8 AM – 11 PM',
    hoursToday: '8:00 AM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Saravana+Bhavan/@28.6279,77.2201',
    keywords: ['dosa','masala dosa','idli','sambar','filter coffee','vada','south indian','vegetarian'],
  },
  {
    id: 'karim-hotel', name: "Karim's",
    region: 'olddelhi', neighbourhood: 'Jama Masjid',
    cuisine: ['indian','street'], vibe: ['casual','budget'],
    type: 'Mughlai Restaurant',
    price: 2, priceLevel: 2, rating: 4.3, ratingCount: 31000,
    location: 'Gali Kababian, Jama Masjid', address: 'Gali Kababian, Jama Masjid, Old Delhi',
    lat: 28.6507, lng: 77.2334,
    intro: "Since 1913 — the most legendary kebab house in Delhi, hidden in a lane behind Jama Masjid.",
    summary: "Since 1913 — legendary kebabs behind Jama Masjid.",
    famous: 'Mutton Burra, Nihari, Seekh Kebab, Biryani',
    tip: 'Go for breakfast nihari on a Sunday.',
    hours: 'Mon–Sun: 9 AM – 12 AM',
    hoursToday: '9:00 AM – 12:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Karim+Hotel/@28.6507,77.2334',
    keywords: ['biryani','kebab','nihari','burra','mutton','mughlai','old delhi','1913'],
    mustTry: true,
  },
  {
    id: 'old-jalebi-wala', name: 'Old Famous Jalebi Wala',
    region: 'olddelhi', neighbourhood: 'Chandni Chowk',
    cuisine: ['street'], vibe: ['budget','casual'],
    type: 'Sweet Shop',
    price: 1, priceLevel: 1, rating: 4.0, ratingCount: 8800,
    location: 'Dariba Kalan, Chandni Chowk', address: 'Dariba Kalan, Chandni Chowk, Old Delhi',
    lat: 28.6562, lng: 77.2297,
    intro: 'Since 1884 — the original desi ghee jalebi, secret recipe through five generations.',
    summary: 'Since 1884 — original desi ghee jalebi, five generations.',
    famous: 'Crispy Desi Ghee Jalebi, Jalebi Rabri, Samosa',
    tip: 'Pair jalebis with cold rabri.',
    hours: 'Mon–Sun: 8 AM – 9:30 PM',
    hoursToday: '8:00 AM – 9:30 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Old+Famous+Jalebi+Wala/@28.6562,77.2297',
    keywords: ['jalebi','rabri','sweets','mithai','ghee','dessert','1884','chandni chowk'],
  },
  {
    id: 'paranthe-wali-gali', name: 'Paranthe Wali Gali',
    region: 'olddelhi', neighbourhood: 'Chandni Chowk',
    cuisine: ['street','indian'], vibe: ['budget','casual'],
    type: 'Street Food',
    price: 1, priceLevel: 1, rating: 4.1, ratingCount: 14000,
    location: 'Paranthe Wali Gali, Chandni Chowk', address: 'Paranthe Wali Gali, Chandni Chowk',
    lat: 28.6566, lng: 77.2290,
    intro: 'A lane dedicated to stuffed paranthas — 150+ years old, fillings from rabri to dry fruit.',
    summary: '150+ year old parantha lane. Fillings from rabri to dry fruit.',
    famous: 'Rabri Parantha, Banana Parantha, Aloo Parantha',
    tip: 'Try at least 3 different fillings.',
    hours: 'Mon–Sun: 7 AM – 10 PM',
    hoursToday: '7:00 AM – 10:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/search/Paranthe+Wali+Gali+Chandni+Chowk',
    keywords: ['paratha','parantha','aloo paratha','stuffed','rabri','breakfast','chandni chowk'],
  },
  {
    id: 'natraj-dahi-bhalle', name: 'Natraj Dahi Bhalle',
    region: 'olddelhi', neighbourhood: 'Chandni Chowk',
    cuisine: ['street'], vibe: ['budget','casual'],
    type: 'Chaat Stall',
    price: 1, priceLevel: 1, rating: 4.5, ratingCount: 6700,
    location: 'Chandni Chowk Main Road', address: 'Chandni Chowk, Old Delhi',
    lat: 28.6558, lng: 77.2301,
    intro: 'Single best dahi bhalle in Delhi — one dish, perfected since 1940.',
    summary: 'Single best dahi bhalle in Delhi. One dish, perfected since 1940.',
    famous: 'Dahi Bhalle, Aloo Tikki Chaat, Papdi Chaat',
    tip: 'Just order the dahi bhalle. Perfected over 80 years.',
    hours: 'Mon–Sat: 9 AM – 9 PM',
    hoursToday: '9:00 AM – 9:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/search/Natraj+Dahi+Bhalle+Chandni+Chowk',
    keywords: ['dahi bhalle','chaat','tikki','papdi','dahi','yogurt','street food'],
  },
  {
    id: 'daryaganj', name: 'Daryaganj',
    region: 'north', neighbourhood: 'Tagore Garden',
    cuisine: ['indian'], vibe: ['casual','finedining'],
    type: 'North Indian Restaurant',
    price: 3, priceLevel: 3, rating: 4.7, ratingCount: 3300,
    location: 'Tagore Garden, North Delhi', address: 'Tagore Garden, New Delhi',
    lat: 28.6659, lng: 77.1333,
    intro: "Self-proclaimed inventors of Butter Chicken and Dal Makhani — the original recipes.",
    summary: "Self-proclaimed inventors of Butter Chicken and Dal Makhani.",
    famous: 'Original Butter Chicken, Dal Makhani, Missi Roti',
    tip: 'Order Butter Chicken + Roomali Roti.',
    hours: 'Mon–Sun: 12 PM – 11 PM',
    hoursToday: '12:00 PM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Daryaganj+Restaurant/@28.6659,77.1333',
    keywords: ['butter chicken','dal makhani','murgh makhani','north indian','original','inventor'],
    mustTry: true,
  },
  {
    id: 'moti-mahal', name: 'Moti Mahal',
    region: 'north', neighbourhood: 'Daryaganj',
    cuisine: ['indian'], vibe: ['casual','budget'],
    type: 'North Indian Restaurant',
    price: 2, priceLevel: 2, rating: 4.0, ratingCount: 5200,
    location: 'Netaji Subhash Marg', address: 'Netaji Subhash Marg, Daryaganj, New Delhi',
    lat: 28.6469, lng: 77.2395,
    intro: 'The original home of butter chicken — opened in 1947, this is where it all started.',
    summary: 'Original home of butter chicken, opened in 1947.',
    famous: 'Butter Chicken, Tandoori Chicken, Dal Makhani',
    tip: 'The OG location. Rough around the edges, food tells the history.',
    hours: 'Mon–Sun: 11 AM – 11 PM',
    hoursToday: '11:00 AM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Moti+Mahal/@28.6469,77.2395',
    keywords: ['butter chicken','tandoori','dal makhani','1947','original','classic'],
  },
  {
    id: 'chache-di-hatti', name: 'Chache Di Hatti',
    region: 'north', neighbourhood: 'Kamla Nagar',
    cuisine: ['street','indian'], vibe: ['budget','casual'],
    type: 'Street Food',
    price: 1, priceLevel: 1, rating: 4.3, ratingCount: 4900,
    location: 'Kamla Nagar, North Delhi', address: 'Kamla Nagar, North Delhi',
    lat: 28.6826, lng: 77.2081,
    intro: "North Delhi's most obsessed-over chole bhature — potato stuffed, always a queue.",
    summary: "Most obsessed-over chole bhature in North Delhi.",
    famous: 'Pindi Chole Bhature, Aloo Bhature, Lassi',
    tip: 'Go before noon. Worth every minute of the queue.',
    hours: 'Mon–Sat: 9:30 AM – 3 PM',
    hoursToday: '9:30 AM – 3:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/search/Chache+Di+Hatti+Kamla+Nagar',
    keywords: ['chole bhature','bhature','chole','pindi','chickpeas','punjabi','breakfast'],
  },
  {
    id: 'wongdhen-cafe', name: 'Wongdhen Cafe',
    region: 'majnu', neighbourhood: 'Majnu Ka Tila',
    cuisine: ['asian'], vibe: ['casual','artsy'],
    type: 'Tibetan Cafe',
    price: 2, priceLevel: 2, rating: 4.4, ratingCount: 2000,
    location: 'Majnu Ka Tila', address: 'Majnu Ka Tila, New Delhi',
    lat: 28.7196, lng: 77.2309,
    intro: "Delhi's Little Tibet — momos, sushi and Japanese cheesecake with live acoustic sets.",
    summary: "Little Tibet — momos, sushi, Japanese cheesecake, live acoustic.",
    famous: 'Corn Dim Sum, Japanese Cheesecake, Crispy Honey Chicken, Momos',
    tip: 'The Japanese cheesecake is exceptional.',
    hours: 'Mon–Sun: 8 AM – 10:30 PM',
    hoursToday: '8:00 AM – 10:30 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Wongdhen+Cafe/@28.7196,77.2309',
    keywords: ['momos','sushi','dim sum','tibetan','japanese cheesecake','dumplings','asian'],
  },
  {
    id: 'dolma-house', name: 'Dolma House',
    region: 'majnu', neighbourhood: 'Majnu Ka Tila',
    cuisine: ['asian'], vibe: ['budget','casual'],
    type: 'Tibetan Restaurant',
    price: 1, priceLevel: 1, rating: 4.3, ratingCount: 1800,
    location: 'Majnu Ka Tila', address: 'Majnu Ka Tila, New Delhi',
    lat: 28.7190, lng: 77.2315,
    intro: 'Beloved Tibetan home-kitchen with the most authentic thukpa and momos in Delhi.',
    summary: 'Beloved Tibetan home-kitchen. Authentic thukpa and momos.',
    famous: 'Beef Thukpa, Steam Momos, Butter Tea',
    tip: 'Try the butter tea — acquired taste, worth it.',
    hours: 'Mon–Sun: 9 AM – 9 PM',
    hoursToday: '9:00 AM – 9:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/search/Dolma+House+Majnu+Ka+Tila',
    keywords: ['thukpa','momos','dumplings','butter tea','tibetan','soup noodles'],
  },
  {
    id: 'andhra-bhavan', name: 'Andhra Bhavan Canteen',
    region: 'lajpat', neighbourhood: 'Ashoka Road',
    cuisine: ['indian','street'], vibe: ['budget','casual'],
    type: 'Government Canteen',
    price: 1, priceLevel: 1, rating: 4.6, ratingCount: 12000,
    location: 'Ashoka Road', address: '1, Ashoka Road, New Delhi',
    lat: 28.6199, lng: 77.2090,
    intro: 'Most under-the-radar legendary meal in Delhi — Andhra thali at government prices.',
    summary: 'Most underrated meal in Delhi — Andhra thali at government prices.',
    famous: 'Andhra Thali, Pesarattu, Gongura Mutton, Pulihora',
    tip: 'Lunch only 12–2 PM. Arrive early — thalis sell out. Under ₹100.',
    hours: 'Mon–Sat: 12 PM – 3 PM',
    hoursToday: '12:00 PM – 3:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Andhra+Bhavan/@28.6199,77.2090',
    keywords: ['thali','andhra','telugu','south indian','gongura','mutton','cheap','spicy'],
    mustTry: true,
  },
  {
    id: 'pindi-restaurant', name: 'Pindi Restaurant',
    region: 'lajpat', neighbourhood: 'Pandara Road',
    cuisine: ['indian'], vibe: ['casual'],
    type: 'North Indian Restaurant',
    price: 3, priceLevel: 3, rating: 4.2, ratingCount: 4400,
    location: 'Pandara Road Market', address: 'Pandara Road Market, New Delhi',
    lat: 28.5994, lng: 77.2153,
    intro: "Pandara Road institution since 1949 — old-school North Indian comfort food.",
    summary: "Pandara Road institution since 1949. Old-school North Indian comfort food.",
    famous: 'Dal Makhani, Pindi Chana, Makki di Roti, Saag',
    tip: 'Pindi wins for the dal. Go after 8 PM.',
    hours: 'Mon–Sun: 12 PM – 12 AM',
    hoursToday: '12:00 PM – 12:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Pindi+Restaurant/@28.5994,77.2153',
    keywords: ['dal makhani','pindi chana','saag','makki roti','rajma','punjabi','1949'],
  },
  {
    id: 'cafe-tesu', name: 'Cafe Tesu',
    region: 'saket', neighbourhood: 'Kalu Sarai',
    cuisine: ['continental','cafe'], vibe: ['casual','artsy'],
    type: 'All-Day Cafe',
    price: 3, priceLevel: 3, rating: 4.3, ratingCount: 5300,
    location: 'Kalu Sarai, near Saket', address: 'Kalu Sarai, New Delhi',
    lat: 28.5433, lng: 77.2066,
    intro: 'All-day neighbourhood cafe — breakfast as seriously as late-night tapas.',
    summary: 'All-day cafe — stellar breakfast and tapas after 8 PM.',
    famous: 'Eggs Benedict, Mac and Cheese with Bacon, Kashmiri Kahwa, Tapas',
    tip: 'Tapas menu kicks in after 8 PM.',
    hours: 'Mon–Sun: 8 AM – 12 AM',
    hoursToday: '8:00 AM – 12:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Cafe+Tesu/@28.5433,77.2066',
    keywords: ['eggs benedict','mac cheese','bacon','tapas','brunch','kahwa','breakfast','all day'],
  },
  {
    id: 'swagath', name: 'Swagath Restaurant',
    region: 'nehru', neighbourhood: 'Defence Colony',
    cuisine: ['indian'], vibe: ['casual','finedining'],
    type: 'Coastal Seafood Restaurant',
    price: 3, priceLevel: 3, rating: 4.4, ratingCount: 6800,
    location: 'Defence Colony', address: 'Defence Colony, New Delhi',
    lat: 28.5653, lng: 77.2373,
    intro: 'Best coastal seafood in landlocked Delhi — Mangalorean and Chettinad done perfectly.',
    summary: 'Best coastal seafood in Delhi — Mangalorean and Chettinad.',
    famous: 'Crab Gassi, Prawn Ghee Roast, Neer Dosa, Fish Curry',
    tip: 'Call ahead for the crab — it sells out.',
    hours: 'Mon–Sun: 12–3:30 PM, 7–11 PM',
    hoursToday: '12:00 PM – 3:30 PM, 7:00 PM – 11:00 PM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Swagath+Restaurant/@28.5653,77.2373',
    keywords: ['crab','prawn','seafood','fish','gassi','ghee roast','neer dosa','mangalorean','chettinad'],
  },
  {
    id: 'punjabi-by-nature', name: 'Punjabi By Nature',
    region: 'nehru', neighbourhood: 'Connaught Place',
    cuisine: ['indian'], vibe: ['casual','finedining'],
    type: 'North Indian Restaurant',
    price: 3, priceLevel: 3, rating: 4.1, ratingCount: 9100,
    location: 'Connaught Place', address: 'Connaught Place, New Delhi',
    lat: 28.6315, lng: 77.2167,
    intro: 'Upscale Punjabi food with a theatrical twist — butter chicken arrives in a surahi.',
    summary: 'Upscale Punjabi — butter chicken in a surahi, Patiala peg cocktails.',
    famous: 'Surahi Butter Chicken, Patiala Peg Cocktails, Amritsari Kulcha',
    tip: 'The cocktail menu is as good as the food.',
    hours: 'Mon–Sun: 12 PM – 12 AM',
    hoursToday: '12:00 PM – 12:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Punjabi+By+Nature/@28.6315,77.2167',
    keywords: ['butter chicken','kulcha','amritsari','saag','cocktails','punjabi','surahi'],
  },
  {
    id: 'olive-bar-kitchen', name: 'Olive Bar & Kitchen',
    region: 'south', neighbourhood: 'Mehrauli',
    cuisine: ['continental','fusion'], vibe: ['romantic','finedining'],
    type: 'Mediterranean Restaurant',
    price: 4, priceLevel: 4, rating: 4.3, ratingCount: 5100,
    location: 'Mehrauli, South Delhi', address: '6, Kalka Das Marg, Mehrauli, New Delhi',
    lat: 28.5244, lng: 77.1855,
    intro: 'Mediterranean dining beside the Qutub Minar — whitewashed walls, fairy lights.',
    summary: 'Mediterranean dining beside Qutub Minar — fairy lights, exceptional food.',
    famous: 'Wood-fired Pizza, Lamb Chops, Sunday Brunch',
    tip: 'Sit outside on a winter night with the Qutub lit up.',
    hours: 'Mon–Sun: 12:30–3 PM, 7 PM–12 AM',
    hoursToday: '12:30 PM – 3:00 PM, 7:00 PM – 12:00 AM',
    isOpenNow: null,
    photo: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    googleMapsUri: 'https://www.google.com/maps/place/Olive+Bar+Kitchen/@28.5244,77.1855',
    keywords: ['pizza','lamb','mediterranean','brunch','qutub','date night','romantic','outdoor'],
  },
]