export type Place = {
  id: string;
  name: string;
  region: string;
  neighbourhood: string;
  cuisine: string[];
  vibe: string[];
  price: number;
  rating: number;
  ratingCount: string;
  location: string;
  intro: string;
  famous: string;
  tip: string;
  hours: string;
  lat: number;
  lng: number;
  photo?: string;
  mustTry?: boolean;
};
